//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronNajaUiPathActivities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MouseionEntities : DbContext
    {
        public MouseionEntities()
            : base("name=MouseionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_amz_arquivos_armazenados> tb_amz_arquivos_armazenados { get; set; }
        public virtual DbSet<tb_dwn_downloads> tb_dwn_downloads { get; set; }
        public virtual DbSet<tb_fky_found_keys> tb_fky_found_keys { get; set; }
        public virtual DbSet<tb_tpo_tipos_origem> tb_tpo_tipos_origem { get; set; }
    }
}
