//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronNajaUiPathActivities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_amz_arquivos_armazenados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_amz_arquivos_armazenados()
        {
            this.tb_dwn_downloads = new HashSet<tb_dwn_downloads>();
            this.tb_fky_found_keys = new HashSet<tb_fky_found_keys>();
        }
    
        public int amz_id { get; set; }
        public string amz_hash { get; set; }
        public string amz_guid { get; set; }
        public string amz_full_path { get; set; }
        public System.DateTime amz_store_datetime { get; set; }
        public string amz_filename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_dwn_downloads> tb_dwn_downloads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fky_found_keys> tb_fky_found_keys { get; set; }
    }
}
