//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronNajaUiPathActivities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tpo_tipos_origem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tpo_tipos_origem()
        {
            this.tb_amz_arquivos_armazenados = new HashSet<tb_amz_arquivos_armazenados>();
        }
    
        public string tpo_sigla { get; set; }
        public string tpo_descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_amz_arquivos_armazenados> tb_amz_arquivos_armazenados { get; set; }
    }
}
